name: Build
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Debug Build Output
        run: ls -al ./dist || echo "dist folder not found!"

      #- name: Run tests
      #  run: npm run test

      - name: Upload production-ready build files
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
